name: golang-s12
on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    types:
      - closed
jobs:
  test:
    runs-on: ubuntu-latest
    container: golang:1.23.4
    steps:
      - uses: actions/checkout@v4

      - name: Init Go module
        run: go mod init

      - name: Run Unit Tests
        run: GOOS=linux GOARCH=amd64 go test

      - name: Vet
        run: |
          go vet ./...

  deploy:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    needs: test
    if: |
      startsWith(github.ref, 'refs/tags') ||
      github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged_at != null
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: westlama/golang-s12

      - name: Build and push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
